[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Partição maior — obrigatório para câmera + servidor web
board_build.partitions = huge_app.csv

; Evita problemas de reset no monitor serial
monitor_rts = 0
monitor_dtr = 0

; Flags necessárias para compilar o servidor de câmera
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; --- BIBLIOTECAS DO PROJETO (Adicionado aqui) ---
lib_deps =
    me-no-dev/AsyncTCP @ ^1.1.1
    marvinroger/AsyncMqttClient @ ^0.9.0